# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/devranaydinoglu/Documents/Dev/ogy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/devranaydinoglu/Documents/Dev/ogy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/devranaydinoglu/Documents/Dev/ogy/CMakeFiles /Users/devranaydinoglu/Documents/Dev/ogy//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/devranaydinoglu/Documents/Dev/ogy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ogy

# Build rule for target.
ogy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ogy
.PHONY : ogy

# fast build rule for target.
ogy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ogy.dir/build.make CMakeFiles/ogy.dir/build
.PHONY : ogy/fast

src/commands/Command.o: src/commands/Command.cpp.o
.PHONY : src/commands/Command.o

# target to build an object file
src/commands/Command.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ogy.dir/build.make CMakeFiles/ogy.dir/src/commands/Command.cpp.o
.PHONY : src/commands/Command.cpp.o

src/commands/Command.i: src/commands/Command.cpp.i
.PHONY : src/commands/Command.i

# target to preprocess a source file
src/commands/Command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ogy.dir/build.make CMakeFiles/ogy.dir/src/commands/Command.cpp.i
.PHONY : src/commands/Command.cpp.i

src/commands/Command.s: src/commands/Command.cpp.s
.PHONY : src/commands/Command.s

# target to generate assembly for a file
src/commands/Command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ogy.dir/build.make CMakeFiles/ogy.dir/src/commands/Command.cpp.s
.PHONY : src/commands/Command.cpp.s

src/commands/info/InfoCommand.o: src/commands/info/InfoCommand.cpp.o
.PHONY : src/commands/info/InfoCommand.o

# target to build an object file
src/commands/info/InfoCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ogy.dir/build.make CMakeFiles/ogy.dir/src/commands/info/InfoCommand.cpp.o
.PHONY : src/commands/info/InfoCommand.cpp.o

src/commands/info/InfoCommand.i: src/commands/info/InfoCommand.cpp.i
.PHONY : src/commands/info/InfoCommand.i

# target to preprocess a source file
src/commands/info/InfoCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ogy.dir/build.make CMakeFiles/ogy.dir/src/commands/info/InfoCommand.cpp.i
.PHONY : src/commands/info/InfoCommand.cpp.i

src/commands/info/InfoCommand.s: src/commands/info/InfoCommand.cpp.s
.PHONY : src/commands/info/InfoCommand.s

# target to generate assembly for a file
src/commands/info/InfoCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ogy.dir/build.make CMakeFiles/ogy.dir/src/commands/info/InfoCommand.cpp.s
.PHONY : src/commands/info/InfoCommand.cpp.s

src/commands/list/ListCommand.o: src/commands/list/ListCommand.cpp.o
.PHONY : src/commands/list/ListCommand.o

# target to build an object file
src/commands/list/ListCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ogy.dir/build.make CMakeFiles/ogy.dir/src/commands/list/ListCommand.cpp.o
.PHONY : src/commands/list/ListCommand.cpp.o

src/commands/list/ListCommand.i: src/commands/list/ListCommand.cpp.i
.PHONY : src/commands/list/ListCommand.i

# target to preprocess a source file
src/commands/list/ListCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ogy.dir/build.make CMakeFiles/ogy.dir/src/commands/list/ListCommand.cpp.i
.PHONY : src/commands/list/ListCommand.cpp.i

src/commands/list/ListCommand.s: src/commands/list/ListCommand.cpp.s
.PHONY : src/commands/list/ListCommand.s

# target to generate assembly for a file
src/commands/list/ListCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ogy.dir/build.make CMakeFiles/ogy.dir/src/commands/list/ListCommand.cpp.s
.PHONY : src/commands/list/ListCommand.cpp.s

src/ogy.o: src/ogy.cpp.o
.PHONY : src/ogy.o

# target to build an object file
src/ogy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ogy.dir/build.make CMakeFiles/ogy.dir/src/ogy.cpp.o
.PHONY : src/ogy.cpp.o

src/ogy.i: src/ogy.cpp.i
.PHONY : src/ogy.i

# target to preprocess a source file
src/ogy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ogy.dir/build.make CMakeFiles/ogy.dir/src/ogy.cpp.i
.PHONY : src/ogy.cpp.i

src/ogy.s: src/ogy.cpp.s
.PHONY : src/ogy.s

# target to generate assembly for a file
src/ogy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ogy.dir/build.make CMakeFiles/ogy.dir/src/ogy.cpp.s
.PHONY : src/ogy.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ogy"
	@echo "... src/commands/Command.o"
	@echo "... src/commands/Command.i"
	@echo "... src/commands/Command.s"
	@echo "... src/commands/info/InfoCommand.o"
	@echo "... src/commands/info/InfoCommand.i"
	@echo "... src/commands/info/InfoCommand.s"
	@echo "... src/commands/list/ListCommand.o"
	@echo "... src/commands/list/ListCommand.i"
	@echo "... src/commands/list/ListCommand.s"
	@echo "... src/ogy.o"
	@echo "... src/ogy.i"
	@echo "... src/ogy.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

